### ISSUE TITLE
API calls via swagger with API key 

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2497]
## Need

As a developer I want to see how API works when browsing Swagger documentation. As developer I want my api key to be inserted automatically in place when ever api_key is required. 

If the api_key is required, I can not as developer try the API from documentation. Thus documentation is not "alive" anymore and crippled. API key requirement is managed by API owner.

**Comment by kyyberi** [comment]
I heard from Vesa that to be able to get api key in use with the swagger, the swagger file needs some modifications. What those are, I have no idea.

**Comment by kyyberi** [comment]
Perhaps something like this http://swagger.io/docs/specification/authentication/api-keys/

**Comment by kyyberi** [comment]
By adding for example the below to swagger, I was able to get API key in place automatically. In other words my api_key was inserted automatically to calls in swagger. 

```
securityDefinitions:
   # X-API-Key: abcdef12345
   APIKeyHeader:
     type: apiKey
     in: header
     name: X-API-Key
   # /path?api_key=abcdef12345
   APIKeyQueryParam:
     type: apiKey
     in: query
     name: api_key

# Global security (applies to all operations):
security:
  - APIKeyHeader: []
```

At least with this Turku API it worked as expected: https://apinf.io/apis/turku-street-maintenance-api
